name: Publish Release
on:
  push:
    tags:
      - '*'
env:
  bintray_user: ${{ secrets.bintray_user }}
  bintray_key: ${{ secrets.bintray_key }}

jobs:
  bintray:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: bintrayUpload
